### ISSUE TITLE
Update to CIS 1.1

### ISSUE THREAD

**Issue by binamov** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#13]
CIS [announced version 1.1](https://www.linkedin.com/posts/the-center-for-internet-security_update-cis-google-cloud-platform-foundation-activity-6645383946739818496-0GzK) improvement to the benchmark, that, among other things: 

> -  Moved the Kubernetes engine section to its own Google Kubernetes Engine (GKE) Benchmark
> - Updated multiple log metric and alert recommendations
> - Updated various Command Line Interface (CLI) commands in both audit and remediation sections

[The latest benchmark](https://www.cisecurity.org/benchmark/google_cloud_computing_platform/) is available for download.

**Comment by dinvlad** [comment]
What's the new location of the GKE controls? Or could we expect a new Inspec benchmark for those?

**Comment by binamov** [comment]
@dinvlad in v 1.1 CIS split up GCP and GKE into separate benchmarks, so we'll move/update the GKE controls in a new repo.

**Comment by dinvlad** [comment]
Thanks! Is there an approximate timeline for the new repo?

**Comment by binamov** [comment]
I'm hoping in the next couple of weeks. @dinvlad feel free to reach out directly if you want to chat about it. You can also create an issue on this repo if you're fine with a couple of weeks and just want to get notified when we're done.

**Comment by binamov** [comment]
@dinvlad https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/pull/33 got merged that should give you better impact scores

**Comment by dinvlad** [comment]
Amazing, thank you!

**Comment by binamov** [comment]
@dinvlad got a chance to port the older controls, https://github.com/GoogleCloudPlatform/inspec-gke-cis-benchmark

**Comment by dinvlad** [comment]
Thanks! Could you please reference the PR? Just for us to double-check which controls.

**Comment by binamov** [comment]
We ported most of the controls that were GKE in CIS GCP 1.0 https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/tree/19718882a742ed2518c06fea20fecbf9945f7619/controls 

There were one or two that did not need to be ported as they are no longer required by the CIS GKE benchmark @dinvlad

**Comment by dinvlad** [comment]
OK, makes sense! Initially I didn't notice the difference in GitHub URLs :)
Thanks a lot!

**Comment by dinvlad** [comment]
Happy to report that we've integrated the new benchmark on our side, and it seems to be working well!
