### ISSUE TITLE
Permissions to scan GCP projects

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#37]
Hi Team,

We're facing a new challenge now as we're trying to scan all projects in a GCP org. We realized we don't really know which minimal IAM permissions the service account running the scans should have. Do you have an exhaustive list of those?

Of course, we could just grant Org Viewer role to that SA, but we'd much prefer to create a custom role with an explicit list of permissions.

Thank you!

**Comment by KonradSchieban** [comment]
Great suggestion @dinvlad . I think this would be very useful to have in the documentation.

**Comment by paulcalabro** [comment]
@KonradSchieban We're looking to scan all projects as well, not just one project. Is there any way to accomplish this atm?

**Comment by dinvlad** [comment]
@paulcalabro we accomplish this right now by submitting a batch jobs where each container scans a single project. Since Inspec is single-threaded (I believe), it may take a long time to scan even a single project. Doing it for N sequentially might be time-prohibiting then..

**Comment by binamov** [comment]
+1 to what dinvlad said, this repo is for a per-project granularity, if you're looking to scan multiple projects a parallel batch job should do it @paulcalabro . The per-project design allows you to enable eg a developer to scan their project in Dev, or to have your CI job scan a project in UAT for which a change is being promoted.

**Comment by paulcalabro** [comment]
Thanks @dinvlad and @binamov for your help! I'll give that a try!

**Comment by dinvlad** [comment]
Hi folks, has there been any progress on this? Thanks!

**Comment by KonradSchieban** [comment]
Hi @dinvlad , I will pick this up and I will provide an update this week.

**Comment by dinvlad** [comment]
@KonradSchieban any updates? Thanks

**Comment by KonradSchieban** [comment]
Hi @dinvlad , sorry for taking so long on this. I have used the IAM Recommender API to suggest the needed permissions for a service account and have added them to the Readme.

Note, that some permissions are needed on org level. So, you can either create a custom role on org level with all listed permissions, such that you can run the profile for any project inside the org. The absolute bare minimum of permissions would be by creating a custom role on org level for the required org permissions and a second custom role with all permissions just for a single project.

The best way depends, of course, on your IAM design (folder structure, multiple environments, different security zones, etc.).

Let me know if the list provided answered your question. Thanks!

**Comment by dinvlad** [comment]
Perfect, thanks so much! We'll most likely set up a dedicated role for this and test it out.

**Comment by dinvlad** [comment]
@KonradSchieban could you add the same for https://github.com/GoogleCloudPlatform/inspec-gke-cis-benchmark please?

**Comment by KonradSchieban** [comment]
> @KonradSchieban could you add the same for https://github.com/GoogleCloudPlatform/inspec-gke-cis-benchmark please?

Eventually yes. We still have many controls to implement for inspec-gke-cis, however.

**Comment by dinvlad** [comment]
I see, thanks! Would you say that Kubernetes Engine Viewer role would be adequate for now?

**Comment by dinvlad** [comment]
Thanks, makes perfect sense! And we're already running both GCP and GKE benchmarks in the same job, so our service account has both GCP and GKE permissions now.

**Comment by KonradSchieban** [comment]
Ah that's awesome! That means we really need to get going with the rest of the GKE CIS controls ;-)

Out of curiosity: Is there anything you see from the IAM Recommender in IAM? If you have overprovisioned the permissions for the service account you should be able to see a lightbulb showing you how many permissions are over granted.

**Comment by dinvlad** [comment]
@KonradSchieban I'd be curious to see that as well! We're only starting to test them together with the updated set of permissions, so we'll need to give the IAM Recommender some time to give us results :)

**Comment by dinvlad** [comment]
We're experiencing something very strange re permissions for GCP CIS scan:

1. We created a Service Account X in Project X, and granted it permissions described in
   [README.md#required-permissions](https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/master/README.md#required-permissions) (plus Kubernetes Engine Viewer), to Project Z.
2. Project Y has associated SA X with the GKE Workload Identity of our benchmark runner deployed in Project Y.
3. We ran the benchmark on Project Z from Project Y with SA X, and collected some findings
4. We then created a separate SA Z in Project Z, to which we granted the same exact permissions in Project Z, and associated it with the GKE Workload Identity of the benchmark runner deployed in Project Z (so everything is in project Z only now).
5. We ran the benchmark on Project Z from Project Z with SA Z, and collected the findings.
6. There turned out to be more findings in step 5 than in step 3!

TD;LR: We get _more_ findings from the benchmark if the SA used to perform scans is located in the _same_ project that is being scanned. If the SA is located in another project, then even when it has the same permissions in the scanned project, it outputs fewer findings.

I'm honestly at a bit of a loss on how to explain this. The "extra" findings are all about Cloud SQL, GKE and some IAM resources. So it appears as if a SA in another project just isn't able to "see" them, despite the same permissions in the target project. Do you have any pointers on why that may be?

Thanks!

**Comment by KonradSchieban** [comment]
Hi @dinvlad , thank you for raising this. I have a suspicion why this is, yet have not experience it myself. My assumption is that some classes which cache results for Cloud SQL, GKE and IAM do not report errors despite not collecting all items due to missing permissions. Ideally, those classes would raise errors and show the missing permissions. This is only my initial thought but will investigate.

Can you please flag this as a new issue with your findings? Thank you!

**Comment by dinvlad** [comment]
Understood, thanks!

I now have a theory also and working to verify it: https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/issues/54#issuecomment-689764742
