### ISSUE TITLE
CIS Control 1.5 doesn't detect correctly 

### ISSUE THREAD

**Issue by akasakashota** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#46]
Hi team,

It seem that the below regex in control of 1.5 is incorrect:
https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/f0f25e016a7d5f8f2df0eb2c3ea433130ac0ee08/controls/1.05-iam.rb#L48
https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/f0f25e016a7d5f8f2df0eb2c3ea433130ac0ee08/controls/1.05-iam.rb#L55
https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/f0f25e016a7d5f8f2df0eb2c3ea433130ac0ee08/controls/1.05-iam.rb#L62

In fact, when I created a service account with `roles/editor` in my project, it was not detected.

According to CIS Control 1.5, it is written as follows.
> This recommendation is only applicable to User-Managed user-created service accounts. These accounts have the nomenclature: SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com.

Therefore, I think it should correctly be a regex such as `/@#{gcp_project_id}.iam.gserviceaccount.com/`.

If I'm not wrong, I'll pull-request the code to fix.

**Comment by KonradSchieban** [comment]
Hi @akasakashota and thank you for raising the issue. Makes sense to me but I will also have to do some testing. A PR is greatly appreciated.

**Comment by dinvlad** [comment]
I think this actually needs to be even more selective! For example, in our project it gets triggered on:
```
service-xxxxxxxxxxxx@containerregistry.iam.gserviceaccount.com | Google Container Registry Service Agent | Editor
```

**Comment by dinvlad** [comment]
So I think it should _exclude_ any of the `service-${PROJECT_ID}@[a-z][a-z0-9|-]{4,28}[a-z].iam.gserviceaccount.com` SAs from consideration.

**Comment by dinvlad** [comment]
(or alternatively, this indicates that `Google Container Registry Service Agent` should not actually be granted `Editor` role by Google, esp. since it's the only one with an admin role!)

**Comment by KonradSchieban** [comment]
> I think this actually needs to be even more selective! For example, in our project it gets triggered on:
> 
> ```
> service-xxxxxxxxxxxx@containerregistry.iam.gserviceaccount.com | Google Container Registry Service Agent | Editor
> ```

That's interesting that your container registry SA causes a failed control because it should not. We included logic in the linked PR to skip the container registry SA because it is by default Editor on the project. Does the SA have any other administrative role?

**Comment by dinvlad** [comment]
Weirdly, yes, the only 2 other Editor SAs in this project are:
```
xxxxxxxxxxxx-compute@developer.gserviceaccount.com
xxxxxxxxxxxx@cloudservices.gserviceaccount.com
```
Yet, we still get a finding (and hard to say which SA it refers to!) that says:
```
Project Editor Role is expected not to include /@[a-z][a-z0-9|-]{4,28}[a-z].iam.gserviceaccount.com/
```

**Comment by dinvlad** [comment]
Unless we didn't rebuild this image since the fix was merged (I'll double-check)..

**Comment by dinvlad** [comment]
Yes, we're on `1.1.0-17`.

**Comment by KonradSchieban** [comment]
OK will investigate!

**Comment by akasakashota** [comment]
FYI it seems to be working fine in my environment.

Just to be sure, are the credentials for running InSpec and the credentials you are using for check the same thing? 

Please try running the following gcloud command with the credentials for running InSpec and check the output.

```bash
$ gcloud projects get-iam-policy <YOUR_PROJECT_ID> --flatten="bindings" --filter="bindings.role=roles/editor" --format='value[delimiter="\n"](bindings.members)'
serviceAccount:xxxxxxxxxxxx-compute@developer.gserviceaccount.com
serviceAccount:xxxxxxxxxxxx@cloudservices.gserviceaccount.com
serviceAccount:service-xxxxxxxxxxxx@containerregistry.iam.gserviceaccount.com
...snip
```

I hope that this information is helpful to you. Thanks.

**Comment by dinvlad** [comment]
OK, sorry for the confusion here :) I overlooked one account earlier. This command helped me clarify that!

**Comment by dinvlad** [comment]
That being said, it would be _really_ helpful if `code_desc` reported the actual email of the violating SA. But that deserves its own issue :)

**Comment by KonradSchieban** [comment]
Just to confirm @dinvlad , the control works as expected, but the code_desc field should contain the email of the violating SA?
