### ISSUE TITLE
cis-gcp-1.3-iam makes it difficult to apply controls programmatically

### ISSUE THREAD

**Issue by KonradSchieban** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#5]
I would like to run InSpec and Terraform programmatically as part of a Cloud Build pipeline. The control cis-gcp-1.3-iam prevents user-managed service accounts, which I require for Terraform and InSpec execution. How can this be achieved without removing the control?

**Comment by TaEduard** [comment]
I believe that this problem is tackled by Vault (https://www.vaultproject.io/) by having service accounts which are short lived and generated on demand.

**Comment by binamov** [comment]
Wondering if we can use `gcloud auth` credentials instead of user managed SSH keys?
