### ISSUE TITLE
Deprecation warning about should_not in 3.09-networking.rb

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#57]
Hi Team,

I noticed a deprecation warning that gets logged every time we run the scanner:
```
Using `should_not` from rspec-expectations' old `:should` syntax
without explicitly enabling the syntax is deprecated.
Use the new `:expect` syntax or explicitly enable `:should`
with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead.
Called from inspec-gcp-cis-benchmark/controls/3.09-networking.rb:47:in
`block (4 levels) in load_with_context'.
```

Is that something known and could be fixed? Obviously, not a big deal, but it does make the logs harder to read :-)

I have set `export RUBYOPT="-W:no-deprecated"`, but that didn't help in this case, as it seems.

Thanks!

**Comment by aaronlippold** [comment]
This article seems to indicate - https://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/. - that we have to just update the expect style blocks to use `.to cmp(blah)` and `.to_not eq(foo)` rather than `.should cmp(blah)` and or `.should_not eq(foo)`.

**Comment by KonradSchieban** [comment]
Thank you @dinvlad for raising this issue and @aaronlippold for suggesting a fix!
