### ISSUE TITLE
Update rspec expect syntax to the `.to` pattern

### ISSUE THREAD

**Issue by aaronlippold** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#60]
#57 

see: https://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/

**Comment by KonradSchieban** [comment]
Hi @aaronlippold , is this issue resolved by https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/pull/68 ? I don't see remaining deprecation warnings.

**Comment by KonradSchieban** [comment]
Closing since there are no remaining deprecation warnings left.
