### ISSUE TITLE
cis-gcp-3.8-networking check is failing because of the internal load balancer proxy subnet typ

### ISSUE THREAD

**Issue by Clausewitz45** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#64]
Hi Team, 

Since Google introduced the proxy-only subnets which are reserved for Internal HTTP(S) Load Balancing, the 3.8 check is failing because of the missing VPC Flow Logs options. I checked on console and gcloud commands - not option to set flow logs when you are creating this type of subnet. 

I don't know the status of the CIS1.2, or does that will contain something like this, but this check should be excluded on that type of subnets otherwise my CSO will execute me. 

Regards,
Csaba

**Comment by binamov** [comment]
This is correct, VPC Flow Logs are not supported for proxy-only subnets as per https://cloud.google.com/load-balancing/docs/l7-internal/proxy-only-subnets#requirements_and_limitations . A pattern like this https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/master/controls/6.01-db.rb#L85 can probably be used to skip validation of proxy-only subnets. Is this a PR you're open to filing @Clausewitz45 ?

**Comment by Clausewitz45** [comment]
Many thanks for the confirmation @binamov - I will give a try to do it tomorrow.

**Comment by binamov** [comment]
Seems the subnetwork object has a `purpose` field and if the value is `INTERNAL_HTTPS_LOAD_BALANCER` then no VPC Flow Logs. https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks

**Comment by KonradSchieban** [comment]
@Clausewitz45 thank you for raining the issue! Can you please check if the linked PR fixes the issue? Thanks!

**Comment by Clausewitz45** [comment]
Hi @KonradSchieban and @binamov . Sorry for not being able to submit the fix, battling with the flu, or whatever. I tested, works fine, and many thanks for closing/fixing it.

**Comment by KonradSchieban** [comment]
No worries and thanks for confirming @Clausewitz45 ! Hope you'll feel better soon!
