### ISSUE TITLE
cis-gcp-3.4-networking check failing because DNSSEC not enabled on private zones

### ISSUE THREAD

**Issue by Clausewitz45** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#67]
Hi Team, 

This control should check only public zones not the private ones, because the `--dnssec-state on` gcloud flag expected only there. No option on the UI, and the API returns with an error:
```
ERROR: (gcloud.dns.managed-zones.update) HTTPError 412: Precondition not met for 'DNSSEC can only be enabled on public zones.'
```
Unfortunately no chance on my side to create a pull request - I don't want to fail miserably like last time. If you have the time/chance and the required knowledge, please go ahead. I will hold the shield against our CSO until that. 

regards,
Csaba

**Comment by Clausewitz45** [comment]
The situation is the same for cis-gcp-3.5-networking also, please see output:
```
  ×  cis-gcp-3.4-networking: [NETWORKING] Ensure that RSASHA1 is not used for key-signing key in Cloud DNS DNSSEC (3 failed)
     ×  [REDACTED] DNS Zone [REDACTED] DNSSEC is expected to cmp == "on"

     expected: on
          got: off

     (compared using `cmp` matcher)

  ×  cis-gcp-3.5-networking: [NETWORKING] Ensure that RSASHA1 is not used for zone-signing key in Cloud DNS DNSSEC (3 failed)
     ×  [REDACTED] DNS Zone [REDACTED] DNSSEC is expected to cmp == "on"

     expected: on
          got: off

     (compared using `cmp` matcher)
```

**Comment by KonradSchieban** [comment]
Hi @Clausewitz45 , thanks for raising this issue. This is a good catch that we should resolve. Please allow us a few days to resolve. Should be straight-forward.

**Comment by KonradSchieban** [comment]
@Clausewitz45 can you please confirm that this PR solved the issue? Thanks!

**Comment by Clausewitz45** [comment]
Hi @KonradSchieban , yes I can confirm. Many thanks for the fix.
