### ISSUE TITLE
[ 2.4-2.11]  issue while creating alerts from the the specified metrics from the gcp cis pdf

### ISSUE THREAD

**Issue by deepakmahajan-23** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#70]
Hi Team,

While implementing the CIS benchmark we faced few issues for the policies from 2.4 to 2.11. Issues are as follow -

1.  when we create an alert based on the given metrics as per the "CIS Google Cloud Platform Foundation Benchmark" pdf documentation from the console. It gives an error saying -> **selected resource is invalid**.
looks like few resource types are not supported.

![image](https://user-images.githubusercontent.com/53002099/98360528-faf81680-204f-11eb-8b0f-ffc7144e864b.png)

2. when we add the values of the alert parameters while creating the monitoring alert as per the document eg. aggregator, threshold value and condition, the generated report gives an error for every parameter. Further I checked the code from the controls folder in the repository for specific policy number, looks like expecting exact value for these parameters. I provided those values too but still the error count increased.

Please provide any solution. Thanks.

**Comment by gbohra** [comment]
Getting the same issue. Please help!

**Comment by KonradSchieban** [comment]
@deepakmahajan-23 @gbohra I also identified the same issues. My suggestion to fix the controls is to remove the "resource.type=" in the metric filter. In addition, the suggested values in the alerting condition seem reasonable, yet arbitrary to me and I didn't see those values called out in the benchmark doc. Hence, suggesting to remove them (see linked PR).
@binamov any thoughts?

**Comment by deepakmahajan-23** [comment]
Hi @KonradSchieban Thanks for the suggestion. I tried creating the policy with the your suggestion. The policy is been created but when I generate the new report, it gives error for aggregation_cross_series_reducer, aggregation_per_series_aligner, condition_threshold_value and aggregation_alignment_period. The values I specified while creating policy are COUNT, ALIGN, 0.001 AND 1 minute (60s) respective to above mentioned parameters.

**Comment by KonradSchieban** [comment]
@deepakmahajan-23 the latest version of the CIS benchmark pdf does not specify any specific threshold values but rather it is suggesting that an alerting policy should exist. Hence, in the linked PR I have removed the checks for the threshold values and only a check for the existence of an alerting policy remains. Please check the last release of the profile (or the current master branch).
