### ISSUE TITLE
Set default value for bucket_logging_ignore_regex

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#71]
Hi Team,

We've just updated to the newest master branch version of the benchmark, and it displays this warning on every run:
```
WARN: Input 'bucket_logging_ignore_regex' does not have a value. Use --input-file or --input to provide a value for 'bucket_logging_ignore_regex' or specify a  value with `input('bucket_logging_ignore_regex', value: 'somevalue', ...)`
```

For other optional inputs, there's a default value in inspec.yaml, but not here. Could you provide one? Perhaps `^$` would work?

Thanks

**Comment by KonradSchieban** [comment]
Hi @dinvlad , thanks for raising this issue. Just had a look at that input parameter and it seems like it's not even used for any control, so I think it should be removed. @binamov do you know what `bucket_logging_ignore_regex` was used for and why it is not used by any control?

**Comment by binamov** [comment]
I think the intent was to help customers ignore failures on buckets where logging was turned off, but it doesn't look like this pattern survived the refactors. Should be fine to remove.
