### ISSUE TITLE
Dockerfile Entrypoint incorrect?

### ISSUE THREAD

**Issue by jtangney** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#76]
Dockerfile has ENTRYPOINT ["inspec"].

However, executing:
> docker run inspec-gcp-cis-benchmark:latest exec...

Gives error:
> starting container process caused "exec: \"inspec\": executable file not found in $PATH": unknown

It works correctly if I override the entrypoint
> docker run --entrypoint=cinc-auditor inspec-gcp-cis-benchmark:latest exec...

The cinc-auditor [docs](https://cinc.sh/start/auditor/) seem to suggest that calls to inspec should redirect to cinc-auditor... but maybe not working inside the container?

**Comment by KonradSchieban** [comment]
Hi @jtangney , good point! Can you please review the linked PR and give your ok to merge?

**Comment by jtangney** [comment]
LGTM, thanks!
