### ISSUE TITLE
CIS GCP 1.2.0 support?

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#88]
Hi Team,

I've noticed that [CIS GCP 1.2.0](https://www.cisecurity.org/benchmark/google_cloud_computing_platform/) has been released - are there any plans to update the existing controls for it? (Same question for the GKE benchmark..)

Thanks!

**Comment by vin-fandemand** [comment]
Really interested to see this...

**Comment by dinvlad** [comment]
Thanks a lot!
